### ISSUE TITLE
how to choose size of the board?

### ISSUE THREAD

**Issue by polemos0108** [alyyousuf7/Weaver#12]
how choose diameter of the circle physical board for best resultat?

**Comment by alyyousuf7** [comment]
Hi @polemos0108, currently there is no way to "choose" the size diameter of the circle as everything is relative.

Unfortunately, you'll have to do play with the config (no of lines, draw color, remove intensity, size of the picture, etc) to come to an optimal result.

Closing the issue for now, please feel free to reopen the issue if you have further questions.
