### ISSUE TITLE
Weaver doesn't run

### ISSUE THREAD

**Issue by gibrie** [alyyousuf7/Weaver#5]
Followed the instructions in Readme section, but when processing stops on line 10 "Frame frame" and adds the remarque: 
You may need to add "import java.awt.Frame;" to the top of your sketch.
To make sketches more portable, imports that are not part of the Processing API were removed in Processing 2.
See the changes page for more information: https://github.com/processing/processing/wiki/Changes
Cannot find a class or type named “Frame”

Where do I have to put the subject (picture), "P" and "L"?

**Comment by alyyousuf7** [comment]
@gibrie, to make it work for now, make sure that the folder name is `Weaver`. (When you download the code as zip, the folder name is usually different than the repository name)

Right now the project is organised in such a way that you may try different examples easily. So to change the image or the number of lines, you will first have to change `Weave.pde` to set a particular example (by default it uses example03). And then in `example.pde`, you can modify the variables such as image, the thread color, number of lines, etc.
