### ISSUE TITLE
rectangular frame

### ISSUE THREAD

**Issue by amirahar** [alyyousuf7/Weaver#6]
Hi
I tried a lot, but I couldn't create a rectangular frame
Help me please

**Comment by alyyousuf7** [comment]
What did you try? Which example are you running?

**Comment by amirahar** [comment]
Hi...
example01 / Frame
Unfortunately, I am a beginner

**Comment by alyyousuf7** [comment]
Replace line 20 in `example.pde` with the following:
```frame = new SquareFrame(min_length, 256);```

Try and let me know.

**Comment by amirahar** [comment]
I replaced line 20 in the example pde with the following
But the square was drawn
I want a rectangle to be drawn
I want to be able to frame the length and width

**Comment by alyyousuf7** [comment]
Oh, Rectangle!

If I remember correctly, I didn’t implement Rectangle frame feature because it would then require GUI Window to have variable ratio (width/height), and it is not allowed in Processing yet.

The window size is set in the setup() function with constants.

**Comment by amirahar** [comment]
I hope you add a rectangle to your project
Thank you very much
