### ISSUE TITLE
Change the number of nodes 

### ISSUE THREAD

**Issue by dandylow** [alyyousuf7/Weaver#7]
Hi, can I do this with the code rn? If yes pls tell me how, this would be very useful for my project.

**Comment by alyyousuf7** [comment]
Yes, the `Weaver.pde` file by default uses the `example03` function defined in `example.pde` file.

Open `example.pde` and modify the `example03` function, you should see the current value `256`. Replace it with the value you wish.

I'll try to make the code easier to update the number of pins and lines as it has been a common issue.
